# Generated by Django 5.0.6 on 2024-07-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='bio',
            field=models.TextField(default='PHD And Master', max_length=50),
            preserve_default=False,
        ),
    ]
