# Generated by Django 5.0.6 on 2024-07-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('course_code', models.PositiveSmallIntegerField()),
                ('topics', models.TextField()),
                ('teacher_in_charge', models.CharField(max_length=20)),
                ('duration', models.PositiveSmallIntegerField()),
                ('students_enrolled', models.PositiveSmallIntegerField()),
                ('department', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('assessment_method', models.CharField(max_length=30)),
            ],
        ),
    ]
